services:
  postgres:
    environment:
      - "POSTGRES_USER=$POSTGRES_USER"
      - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
    image: "focker.ir/postgres:latest"
    networks:
      - "dockernet"
    ports:
      - "5432:5432/tcp"
    restart: "always"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
    driver: local

networks:
  dockernet:
    external: true
    name: "dockernet"
